#@TYPE: Machine
#@NAME: scai-navc
#@SOC: Polarfire SoC
#@DESCRIPTION: Machine configuration for the Microchip Polarfire SoC, SpacecraftAI NAVC

#based on icicle-kit-es-nand.conf

require include/mpfs-common.inc

IMAGE_INSTALL:remove = " dt-overlay-mchp"

# 3Dplus-MTD systemd script for auto-format and auto-mount
IMAGE_INSTALL:append = " 3dplus-mtd"

# openembedded-core/meta/recipes-core/systemd/systemd-serialgetty/serial-getty@.service
# 33 ExecStart=-/sbin/agetty -8 -L %I @BAUDRATE@ $TERM
#
# is configured to below baud rate
#
# build/tmp-glibc/work/scai_dpu-oe-linux/core-image-minimal-mtdutils/1.0/rootfs/lib/systemd/system/serial-getty@.service
# 33 ExecStart=-/sbin/agetty -8 -L %I 921600 $TERM
SERIAL_CONSOLES = "921600;ttyS1"

MACHINE_TYPE = "smp"

RISCV_SBI_FDT ?=  "scai-dpu.dtb"
KERNEL_DTC_FLAGS += "-@"
KERNEL_DEVICETREE ?= "microchip/${RISCV_SBI_FDT}"

UBOOT_CONFIG = "scai_dpu"
UBOOT_CONFIG[scai_dpu] = "scai_dpu_defconfig"

# UBIFS for Mikroe FLash 5 Click (128 MB)
MKUBIFS_ARGS ?= " -e 126976 -c 926 -m 2048 -x zlib -F"
UBINIZE_ARGS ?= " -m 2048 -p 128KiB -s 2048"

MPFS_MTDPARTS = "spi0.0:2m(payload),119m(ubi)"
MPFS_IS_ON_MTDID = "spi0.0"
MPFS_MTD_TYPE = "nand"
UBI_VOLNAME = "ubi"

IMAGE_CLASSES:append = " image_type_mtd image_type-ubimage"
IMAGE_FSTYPES = "  mtd ubifs ubimg"
UBI_ROOTFS_SIZE = "16"

UBOOT_ENV = "boot"
UBOOT_ENV_SUFFIX = "scr"
UBOOT_ENV_SIZE = "0x2000"

HSS_PAYLOAD = "uboot"

IMAGE_BOOT_FILES ?= " \
    fitImage \
    boot.scr \
"

WKS_FILE ?= "mpfs-rootfs.wks"

MACHINEOVERRIDES =. "scai-dpu:"
